--- Script ....: 008_TBL_TEMP_EMPRESAS
--- Autor......: José Vinicius
--- Data ......: 30/07/2024
--- Descrição..: Criação da tabela TEMP_EMPRESAS e definição de chave estrangeira
--- Documento..: 

SET DEFINE ON
SET SCAN ON
SET ECHO ON ;
SET FEEDBACK ON ;

DEFINE TSI_DESENV=&TSI_DESENV;  
DEFINE USUARIO_OWNER=&USUARIO_OWNER;

SET SERVEROUTPUT ON
SET SERVEROUTPUT ON SIZE UNLIMITED

BEGIN 
 DBMS_OUTPUT.PUT_LINE('ESQUEMA EXECUTOR =>"' || USER || '" ESQUEMA A SER ATUALIZADO => "&USUARIO_OWNER"  TABLESPACE INDICE => "&TSI_DESENV"   DATA =>' || SYSDATE );   
END;
/

ALTER SESSION SET CURRENT_SCHEMA=&USUARIO_OWNER;

DECLARE 
 V_CONT NUMBER;
 NOME_SCRIPT VARCHAR2(100);
 NUM_VERSAO  NUMBER ; 
BEGIN 
 BEGIN --  
    DBMS_OUTPUT.ENABLE(null); 
   NOME_SCRIPT := '008_TBL_TEMP_EMPRESAS';
   NUM_VERSAO := 988;

   IF "&USUARIO_OWNER".FNC_SCRIPT_EXISTE_LOG(NOME_SCRIPT,NUM_VERSAO)  THEN 

       BEGIN --
        V_CONT:=0;
        
        SELECT COUNT(*) INTO V_CONT FROM ALL_TABLES T WHERE T.owner = UPPER('&USUARIO_OWNER') AND T.table_name = 'TEMP_EMPRESAS'; 
       EXCEPTION
        WHEN OTHERS THEN
         V_CONT:=0;
        END; 
      
       IF V_CONT = 0 THEN 
        EXECUTE IMMEDIATE ' 
          CREATE TABLE &USUARIO_OWNER' || '.TEMP_EMPRESAS (
            NOME VARCHAR2(100),
            RAMO_ATUACAO VARCHAR2(100),
            ENDERECO VARCHAR2(200),
            CIDADE VARCHAR2(100),
            FATURAMENTO NUMBER,
            CODG_FUNCIONARIO_PK NUMBER
          ) ' 
          ;
        
        EXECUTE IMMEDIATE 'ALTER TABLE &USUARIO_OWNER' || '.TEMP_EMPRESAS ADD CONSTRAINT FK_EMP_FUNC FOREIGN KEY (CODG_FUNCIONARIO_PK) REFERENCES &USUARIO_OWNER' || '.TEMP_FUNCIONARIOS (CODG_FUNCIONARIO_PK)';
    
        EXECUTE IMMEDIATE 'ALTER TABLE &USUARIO_OWNER' || '.TEMP_EMPRESAS ADD CONSTRAINT PK_TEMP_EMPRESAS PRIMARY KEY (CODG_FUNCIONARIO_PK) USING INDEX TABLESPACE &TSI_DESENV ';
    
        EXECUTE IMMEDIATE 'CREATE INDEX &USUARIO_OWNER' || '.IDX_TEMP_EMPRESAS_CIDADE ON &USUARIO_OWNER' || '.TEMP_EMPRESAS (CIDADE) TABLESPACE &TSI_DESENV ';
    
        EXECUTE IMMEDIATE 'ALTER TABLE &USUARIO_OWNER' || '.TEMP_EMPRESAS MODIFY FATURAMENTO CONSTRAINT CK_NN_FATURAMENTO NOT NULL ';
    
        EXECUTE IMMEDIATE 'ALTER TABLE &USUARIO_OWNER' || '.TEMP_EMPRESAS ADD CONSTRAINT CK_FATURAMENTO CHECK(FATURAMENTO >= 0) ';
    
        DBMS_OUTPUT.PUT_LINE('TABELA TEMP_EMPRESAS CRIADA COM SUCESSO');   
       ELSE
        DBMS_OUTPUT.PUT_LINE('TABELA TEMP_EMPRESAS JÁ FOI CRIADA');
       END IF;
    
    COMMIT;
    
    --- Inserção em RB_JOIN
      INSERT INTO "&USUARIO_OWNER".RB_JOIN(TABLE_NAME1,TABLE_NAME2,JOIN_TYPE,FIELD_NAMES1,OPERATORS,FIELD_NAMES2)
         SELECT * FROM (
          SELECT 'TEMP_EMPRESAS' AS TABLE_NAME1 ,'TEMP_FUNCIONARIOS' AS TABLE_NAME2 ,'dajtInner' AS JOIN_TYPE,'CODG_FUNCIONARIO_PK' AS FIELD_NAMES1 ,'=' AS OPERATORS ,'CODG_FUNCIONARIO_PK' AS FIELD_NAMES2 FROM DUAL
         ) V
         WHERE NOT EXISTS(
          SELECT * FROM "&USUARIO_OWNER".RB_JOIN T
           WHERE T.TABLE_NAME1 = V.TABLE_NAME1 AND T.TABLE_NAME2 = V.TABLE_NAME2
         )  ;                  
                     
        ----------- Inversão relação gerador Relatório ---------------  
     
     COMMIT;   

  END IF; -- EXISTE LOG

 "&USUARIO_OWNER".PCR_SCRIPT_LOG(NOME_SCRIPT,NUM_VERSAO,'EXECUTADO COM SUCESSO','S');
 EXCEPTION
   WHEN OTHERS THEN 
   ROLLBACK;
   "&USUARIO_OWNER".PCR_SCRIPT_LOG(NOME_SCRIPT,NUM_VERSAO,SQLERRM,'N');
   dbms_output.put_line(SQLERRM);
  END; 
   
END;
/
